---
title: "Sumários, parte 1"
output: html_notebook
---

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
theme_set(theme_bw())
```

```{r}
clima_tudo = read_csv(
    here("data/tempo-jp-cg-pt.csv"),
    col_types = cols(
        .default = col_double(),
        cidade = col_character(),
        semana = col_date(format = ""),
        ano = col_integer(),
        mes = col_integer()
    )
)

clima10 = clima_tudo %>% 
    filter(ano <= 2019, ano >= 2010, !is.na(temp_max))

glimpse(clima10)
```
```{r}
clima10 %>% 
    ggplot(aes(x = ano, y = temp_max)) +
    facet_wrap(~ cidade) +
    geom_point(alpha = .5, size = .9) + 
    labs(
        y = "Calor"
    )
```

```{r}
sumarios = clima10 %>% 
    group_by(cidade, ano) %>% 
    summarise(temp_max_anual = max(temp_max), 
              temp_min_anual = min(temp_max),
              # metade = quantile(temp_max, .5),
              temp_metade = median(temp_max),
              chuva_max = max(chuva), 
              chuva_mediana = median(chuva), 
              chuva_min = min(chuva),
              chuva_90perc = quantile(chuva, .9),
              .groups = "drop")
```

```{r}
sumarios %>% 
    ggplot(aes(x = ano, y = temp_max_anual)) + 
    facet_wrap(~ cidade) +
    geom_point()
```

```{r}
clima10 %>% 
    ggplot(aes(x = ano, y = temp_max)) +
    facet_wrap(~ cidade) +
    geom_point(alpha = .75, size = .9, color = "grey") + 
    geom_point(data = sumarios, aes(y = temp_max_anual)) + 
    geom_point(data = sumarios, aes(y = temp_min_anual)) + 
    geom_point(data = sumarios, aes(y = temp_metade), color = "red") + 
    labs(
        y = "Calor"
    )
```

```{r}
clima10 %>% 
    ggplot(aes(x = ano, y = chuva)) +
    facet_wrap(~ cidade) +
    geom_point(alpha = .5, size = .9, color = "steelblue") + 
    geom_point(data = sumarios, aes(y = chuva_max), color = "black") + 
    geom_point(data = sumarios, aes(y = chuva_min), color = "black") + 
    geom_point(data = sumarios, aes(y = chuva_mediana), color = "red") + 
    labs(
        y = "Chuva"
    )
```

```{r}
clima10 %>% 
    ggplot(aes(x = ano, y = chuva)) +
    facet_wrap(~ cidade) +
    geom_point(alpha = .5, size = .9, color = "steelblue") + 
    geom_point(data = sumarios, aes(y = chuva_90perc), color = "black") + 
    geom_point(data = sumarios, aes(y = chuva_min), color = "black") + 
    geom_point(data = sumarios, aes(y = chuva_mediana), color = "red") + 
    labs(
        y = "Chuva"
    )
```

